name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Test
        run: |
          set -x
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
          anchor init foo
          cd foo
          anchor test
