name: CI

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Anchor prerequisites on Ubuntu
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: sudo apt install libudev-dev

      # - name: Install gnu-sed on MacOS
      #   if: ${{ matrix.environment == 'macos-latest' }}
      #   run: |
      #     brew install coreutils gnu-sed llvm protobuf
      #     echo "/opt/homebrew/opt/gnu-sed/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Test
        run: |
          set -x

          file ./a.sh

          # Install Solana
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

          # Make a key
          mkdir -p $HOME/.config/solana
          cp etc/rfc8032_test_vector.json $HOME/.config/solana/id.json

          # Install Anchor
          cargo install --git https://github.com/solana-foundation/anchor --tag v0.32.1 anchor-cli || true

          cd foo

          yarn

          ../anchor-test-hack.sh foo

          ls -l test-ledger

          cat test-ledger/validator-*.log | grep DEBUG

      # https://github.com/actions/cache/tree/main/save#always-save-cache
      - uses: actions/cache/save@v4
        # smoelius: Update the cache regardless of whether a cache hit occurred, in case further
        # progress was made.
        if: always() # && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
