name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Test
        run: |
          set -x
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          mkdir -p $HOME/.config/solana
          cp etc/rfc8032_test_vector.json $HOME/.config/solana/id.json
          cargo install --git https://github.com/solana-foundation/anchor --tag v0.31.1 anchor-cli
          anchor init foo
          cd foo
          anchor test
